### ISSUE TITLE
Metadata version mismatch

### ISSUE THREAD

**Issue by ashavyshakh** [eakoriakin/ionic-select-searchable#35] opened 2018-05-02 09:39 UTC
Hi ,
Any solution found for this bug?

**Comment by eakoriakin** [comment] 2018-05-03 13:10
Hey, can you try this?
https://github.com/eakoriakin/ionic-select-searchable/issues/12#issuecomment-382639265

Closing this task as a duplicate of https://github.com/eakoriakin/ionic-select-searchable/issues/3.

**Closed by eakoriakin** 2018-05-03 13:10 UTC

**Comment by ashavyshakh** [comment] 2018-05-04 03:50
I ve tried the following ,as per [#12 (comment)](https://github.com/eakoriakin/ionic-select-searchable/issues/12#issuecomment-382639265)
in my ap.module.ts
`import { SelectSearchableModule } from 'ionic-select-searchable';

@NgModule({
imports: [
SelectSearchableModule
]
})
`
and I have another page "page_one.component.ts" where I use this pluggin .in ts file I have added
`import { SelectSearchableModule } from 'ionic-select-searchable';
`
But I am getting the same error.Also i have updated plugin version to 1.0.14. But didnt worked.
My packge.json is given below

{
  "name": "myApp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@ionic-native/badge": "^4.4.2",
    "@ionic-native/call-number": "^4.3.1",
    "@ionic-native/camera": "^4.2.1",
    "@ionic-native/core": "^3.12.1",
    "@ionic-native/crop": "^4.2.1",
    "@ionic-native/device": "^4.3.2",
    "@ionic-native/email-composer": "^4.3.1",
    "@ionic-native/fcm": "^4.3.2",
    "@ionic-native/file": "^4.2.1",
    "@ionic-native/file-path": "^4.2.1",
    "@ionic-native/file-transfer": "^4.2.1",
    "@ionic-native/network": "^4.3.2",
    "@ionic-native/splash-screen": "^3.12.1",
    "@ionic-native/status-bar": "3.12.1",
    "@ionic-native/toast": "^4.2.1",
    "@ionic-native/transfer": "^3.14.0",
    "@ionic-native/wheel-selector": "^4.6.0",
    "@ionic/storage": "2.0.1",
    "angular-svg-round-progressbar": "^1.0.5",
    "angular2-modal": "^3.0.2",
    "angular2-moment": "^1.7.0",
    "chart.js": "^2.7.2",
    "cordova-android": "^6.2.3",
    "cordova-browser": "^4.1.0",
    "cordova-plugin-app-version": "~0.1.9",
    "cordova-plugin-badge": "~0.8.5",
    "cordova-plugin-camera": "^2.4.1",
    "cordova-plugin-compat": "^1.1.0",
    "cordova-plugin-console": "^1.0.5",
    "cordova-plugin-crop": "^0.4.0",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-email-composer": "~0.8.10",
    "cordova-plugin-fcm": "~2.1.2",
    "cordova-plugin-file": "^4.0.0",
    "cordova-plugin-file-transfer": "^1.6.3",
    "cordova-plugin-network-information": "~1.3.3",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.2",
    "cordova-plugin-whitelist": "^1.3.1",
    "cordova-plugin-x-toast": "^2.6.0",
    "ionic-angular": "3.6.0",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionic-select-searchable": "1.0.14",
    "ionic2-super-tabs": "^4.2.2",
    "ionicons": "3.0.0",
    "jquery": "^3.2.1",
    "lodash": "^4.17.4",
    "mx.ferreyra.callnumber": "~0.0.2",
    "ng-intl-tel-input": "^2.0.0",
    "rxjs": "5.4.0",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@ionic/app-scripts": "2.1.3",
    "@ionic/cli-plugin-cordova": "1.6.2",
    "@ionic/cli-plugin-ionic-angular": "1.4.1",
    "ionic": "3.20.0",
    "typescript": "2.3.4"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-console": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "ionic-plugin-keyboard": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-x-toast": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-file": {},
      "cordova-plugin-crop": {},
      "cordova-plugin-app-version": {},
      "cordova-plugin-email-composer": {},
      "cordova-plugin-fcm": {},
      "cordova-plugin-network-information": {},
      "mx.ferreyra.callnumber": {},
      "cordova-plugin-badge": {}
    },
    "platforms": [
      "android",
      "browser"
    ]
  },
  "config": {
    "ionic_sass": "src/config/sass.config.js"
  }
}

Please kindly update , if there any solution
