### ISSUE TITLE
has no exported member SelectSearchableComponent and SelectSearchableModule

### ISSUE THREAD

**Issue by kodeine** [eakoriakin/ionic-select-searchable#50] opened 2018-05-20 19:51 UTC
Any idea what's going on?

```
[14:50:00]  typescript: src/pages/users/new/users.new.page.module.ts, line: 4 
            Module '"/Projects/node_modules/ionic-select-searchable/ionic-select-searchable"' 
            has no exported member 'SelectSearchableModule'. 

       L3:  import {UserNewPage} from "./users.new.page";
       L4:  import {SelectSearchableModule} from "ionic-select-searchable";


[14:48:17]  typescript: src/pages/users/new/users.new.page.ts, line: 12 
            Module '"/Projects/node_modules/ionic-select-searchable/ionic-select-searchable"' 
            has no exported member 'SelectSearchableComponent'. 

      L11:  import {AuthService} from "../../../services/auth.service";
      L12:  import {SelectSearchableComponent} from "ionic-select-searchable";
```

```
cli packages: (/Projects/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v9.2.1
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/user/Library/Android/sdk

Misc:

    backend : legacy
```

**Comment by kodeine** [comment] 2018-05-21 10:39
Im already importing it on every lazy module and I also had to import it in app.module. same issue. And my error is different than the one listed in faqs.

**Comment by eakoriakin** [comment] 2018-05-21 10:40
Okay, can you share a repo with this error so I could helpl you?

**Comment by kodeine** [comment] 2018-05-21 10:41
It's a big project, let me try to create a minimal project and share that.

**Comment by kodeine** [comment] 2018-05-21 18:49
can you take a look using teamviewer?

**Comment by eakoriakin** [comment] 2018-05-21 18:59
Sorry, I can’t do that

**Comment by kodeine** [comment] 2018-05-21 21:26
ill make a test repo and get back to you

**Comment by salcott** [comment] 2018-05-23 18:20
Also experiencing this

**Comment by eakoriakin** [comment] 2018-05-23 18:21
I need a repo to reproduce the error guys. I can’t help you without it

**Comment by salcott** [comment] 2018-05-23 18:39
Thanks for your quick response. My problem turned out to be that my lazy loaded page had its own discover.module.ts file where `IonicModule.forRoot(DiscoverPage)` was used. The solve you included above did the fix for me.

**Comment by kodeine** [comment] 2018-05-23 18:53
@salcott so this is what my lazy loaded page module looks like, what exactly did you change?

```
import {NgModule} from '@angular/core';
import {IonicPageModule} from 'ionic-angular';
import {TeamNewPage} from "./teams.new.page";
import {NoticeModalComponentModule} from "../../../components/notice-modal/notice.modal.page.module";
import {SelectSearchableModule} from "ionic-select-searchable";


@NgModule({
    declarations: [TeamNewPage],
    imports: [
        IonicPageModule.forChild(TeamNewPage),
        SelectSearchableModule,
        NoticeModalComponentModule,
    ],
    exports: [TeamNewPage],
})
export class TeamNewPageModule { }
```

**Comment by salcott** [comment] 2018-05-27 18:01
@kodeine that matches my lazy loaded page module which is working.  `SelectSearchableModule` is also imported in `app.module.ts` as `import { SelectSearchableModule } from 'ionic-select-searchable';
` and listed in `imports` as `SelectSearchableModule`

**Comment by eakoriakin** [comment] 2018-06-01 12:11
Closing the issue as I couldn't reproduce it. Feel free to reopen it any time if you have a repo with this error.

**Closed by eakoriakin** 2018-06-01 12:11 UTC
Labels: question

**Comment by kodeine** [comment] 2018-06-02 16:05
@eakoriakin i was able to find the problem, `"typescript": "^2.8.0-insiders.20180127",` was  the issue. I downgraded to `^2.4.2`.

**Comment by kodeine** [comment] 2018-06-02 19:38
@eakoriakin can you make this work with typescript 2.8.0 or >=2.6

**Comment by eakoriakin** [comment] 2018-06-03 05:39
Hi @kodeine, I tried the latest `typescript@2.9.1` on [demo](https://github.com/eakoriakin/ionic-select-searchable-demo) project and both `ionic serve` and `ionic cordova build android --prod --release` worked fine.
